-- MySQL Script generated by MySQL Workbench
-- Qua 19 Abr 2017 14:39:42 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema leishdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leishdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leishdb` DEFAULT CHARACTER SET utf8 ;
USE `leishdb` ;

-- -----------------------------------------------------
-- Table `leishdb`.`organisms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`organisms` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organism` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`chromosomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`chromosomes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gbid` VARCHAR(255) NOT NULL,
  `number` INT(11) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `sequence` LONGTEXT NOT NULL,
  `size` INT(11) NOT NULL,
  `organism_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chromosomes_organisms1_idx` (`organism_id` ASC),
  CONSTRAINT `fk_chromosomes_organisms1`
    FOREIGN KEY (`organism_id`)
    REFERENCES `leishdb`.`organisms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`proteins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`proteins` (
  `id` VARCHAR(255) NOT NULL,
  `entryname` TEXT NOT NULL,
  `proteinname` TEXT NOT NULL,
  `genename` VARCHAR(255) NOT NULL,
  `organism` VARCHAR(255) NOT NULL,
  `taxonomiclineage` TEXT NULL DEFAULT NULL,
  `proteinfamily` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`databases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`databases` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `urlbyintegration` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`genes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`genes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `start` INT(11) NOT NULL,
  `end` INT(11) NOT NULL,
  `strand` VARCHAR(255) NOT NULL,
  `size` INT(11) NOT NULL,
  `protein_id` VARCHAR(255) NOT NULL,
  `chromosome_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_genes_proteins1_idx` (`protein_id` ASC),
  INDEX `fk_genes_chromosomes1_idx` (`chromosome_id` ASC),
  CONSTRAINT `fk_genes_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `leishdb`.`proteins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genes_chromosomes1`
    FOREIGN KEY (`chromosome_id`)
    REFERENCES `leishdb`.`chromosomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`crossreference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`crossreference` (
  `referenceid` VARCHAR(255) NOT NULL,
  `protein_id` VARCHAR(255) NULL,
  `gene_id` INT(11) UNSIGNED NULL,
  `database_id` BIGINT(20) NOT NULL,
  INDEX `‡í+fk_crossreference_databases1_idx` (`database_id` ASC),
  INDEX `fk_crossreference_genes1_idx` (`gene_id` ASC),
  CONSTRAINT `fk_crossreference_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `leishdb`.`proteins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crossreference_databases1`
    FOREIGN KEY (`database_id`)
    REFERENCES `leishdb`.`databases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crossreference_genes1`
    FOREIGN KEY (`gene_id`)
    REFERENCES `leishdb`.`genes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`geneontology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`geneontology` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `type` CHAR(1) NOT NULL COMMENT 'm - molecular\nb - biological\nc - component',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`ncrna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`ncrna` (
  `id` INT(11) UNSIGNED NOT NULL,
  `chromosome_id` INT(11) UNSIGNED NOT NULL,
  `family` TEXT NULL DEFAULT NULL,
  `start` INT(11) NOT NULL,
  `end` INT(11) NOT NULL,
  `type` TEXT NULL DEFAULT NULL,
  `predictor` TEXT NULL DEFAULT NULL,
  `covariancemodel` VARCHAR(10) NOT NULL,
  `similarity` VARCHAR(10) NOT NULL,
  `transcript` VARCHAR(10) NOT NULL,
  `havetargetgenes` VARCHAR(10) NOT NULL,
  `conservedspecies` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ncrna_chromosomes1_idx` (`chromosome_id` ASC),
  CONSTRAINT `fk_ncrna_chromosomes1`
    FOREIGN KEY (`chromosome_id`)
    REFERENCES `leishdb`.`chromosomes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`proteinsgo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`proteinsgo` (
  `protein_id` VARCHAR(255) NOT NULL,
  `geneontology_id` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_proteinsgo_geneontology1_idx` (`geneontology_id` ASC),
  CONSTRAINT `fk_proteinsgo_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `leishdb`.`proteins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proteinsgo_geneontology1`
    FOREIGN KEY (`geneontology_id`)
    REFERENCES `leishdb`.`geneontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `leishdb`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leishdb`.`publications` (
  `pubmedid` VARCHAR(255) NOT NULL,
  `protein_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pubmedid`, `protein_id`),
  INDEX `fk_publications_proteins1_idx` (`protein_id` ASC),
  CONSTRAINT `fk_publications_proteins1`
    FOREIGN KEY (`protein_id`)
    REFERENCES `leishdb`.`proteins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
